import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div className='min-h-screen relative md:flex'>
          <Navbar />
          <main className='w-full md:ml-72 mt-12 md:w-auto md:flex-1 overflow-auto'>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
